package com.amgqa.kata.models;

import jakarta.validation.constraints.*;

public class Booking {

    private Integer bookingid;  // generated by API

    @NotNull
    private Integer roomid;

    @NotBlank
    @Size(min = 3, max = 18)
    private String firstname;

    @NotBlank
    @Size(min = 3, max = 30)
    private String lastname;

    @NotNull
    private Boolean depositpaid;

    @NotBlank
    @Email
    private String email;

    @NotBlank
    @Size(min = 11, max = 21)
    private String phone;

    @NotNull
    private BookingDates bookingdates;

    // Constructors, getters only
    public Booking() {}

    public Booking(Integer roomid, String firstname, String lastname, Boolean depositpaid, String email, String phone, BookingDates bookingdates) {
        this.roomid = roomid;
        this.firstname = firstname;
        this.lastname = lastname;
        this.depositpaid = depositpaid;
        this.email = email;
        this.phone = phone;
        this.bookingdates = bookingdates;
    }

    public Integer getBookingid() {
        return bookingid;
    }

    public Integer getRoomid() {
        return roomid;
    }

    public String getFirstname() {
        return firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public Boolean getDepositpaid() {
        return depositpaid;
    }

    public String getEmail() {
        return email;
    }

    public String getPhone() {
        return phone;
    }

    public BookingDates getBookingdates() {
        return bookingdates;
    }
}
